# Generated by Django 5.0.3 on 2024-04-01 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitSummary', models.CharField(max_length=500)),
                ('prescriptions', models.CharField(max_length=500)),
                ('labWork', models.CharField(max_length=500)),
                ('patientId', models.IntegerField()),
                ('doctorId', models.IntegerField()),
                ('createdDate', models.DateTimeField(default=datetime.datetime(2024, 4, 1, 23, 54, 35, 115988, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
