# Generated by Django 5.0.3 on 2024-03-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField()),
                ('doctorId', models.IntegerField()),
                ('createdDate', models.DateTimeField()),
            ],
        ),
    ]
