# Generated by Django 5.0.3 on 2024-04-01 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='createdDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 1, 23, 54, 35, 115347, tzinfo=datetime.timezone.utc)),
        ),
    ]
